### IQR & Outliers

In [190]:
import numpy as np
import pandas as pd

In [191]:
dataset = pd.read_csv("Placement.csv")

In [192]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [193]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [194]:
dataset["hsc_s"].value_counts()

hsc_s
Commerce    113
Science      91
Arts         11
Name: count, dtype: int64

In [195]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [196]:
dataset.describe()
# It will show only for numerical data (Since its applicable for numbers)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [197]:
from Univariate import Univariate 

qual, quan = Univariate.get_qual_quan(dataset)

In [198]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [199]:
descriptive = pd.DataFrame(
    index=[
        "Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%","Q4:100%", 
        "IQR", "1.5_Rule", "Lower_Boundary", "Upper_Boundary", "Min", "Max",
        "Has_Lower_Outlier",
        "Has_Upper_Outlier"
    ],
    columns=quan
)

In [200]:
descriptive.columns

Index(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'], dtype='object')

In [201]:
dataset[column].mean()

np.float64(288655.4054054054)

In [202]:
dataset[column].median()

265000.0

In [203]:
dataset[column].mode()[0]

np.float64(300000.0)

### Finding Outliers
- Since got following error, I used the .loc method
- SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

In [204]:
# for column in quan:
    # print(descriptive[column]["Mean"])
    # descriptive[column]["Mean"] = dataset[column].mean()
    # descriptive[column]["Median"] = dataset[column].median()
    # descriptive[column]["Mode"] = dataset[column].mode()[0]
    
    # following will handle the NaN/missing values
    # descriptive[column]["Q1:25%"] = dataset.describe()[column]["25%"]
    # descriptive[column]["Q2:50%"] = dataset.describe()[column]["50%"]
    # descriptive[column]["Q3:75%"] = dataset.describe()[column]["75%"]
    # descriptive[column]["99%"] = np.percentile(dataset[column], 99)
    # descriptive[column]["Q4:100%"] = dataset.describe()[column]["max"]

    # IQR
    # descriptive[column]["IQR"] = descriptive[column]["Q3:75%"] - descriptive[column]["Q1:25%"]
    # descriptive[column]["1.5_Rule"] = 1.5 * descriptive[column]["IQR"]
    # descriptive[column]["Lesser"] = descriptive[column]["Q1:25%"] - descriptive[column]["1.5_Rule"]
    # descriptive[column]["Greater"] = descriptive[column]["Q3:75%"] + descriptive[column]["1.5_Rule"]
    # descriptive[column]["Min"] = dataset.describe()[column]["min"]
    # descriptive[column]["Max"] = dataset.describe()[column]["max"]

In [205]:
for column in quan:
    descriptive.loc["Mean", column] = dataset[column].mean()
    descriptive.loc["Median", column] = dataset[column].median()
    descriptive.loc["Mode", column] = dataset[column].mode()[0]
    
    # following will handle the NaN/missing values
    descriptive.loc["Q1:25%", column] = dataset.describe()[column]["25%"]
    descriptive.loc["Q2:50%", column] = dataset.describe()[column]["50%"]
    descriptive.loc["Q3:75%", column] = dataset.describe()[column]["75%"]
    descriptive.loc["99%", column] = np.percentile(dataset[column], 99)
    descriptive.loc["Q4:100%", column] = dataset.describe()[column]["max"]

    # IQR
    descriptive.loc["IQR", column] = descriptive[column]["Q3:75%"] - descriptive[column]["Q1:25%"]
    descriptive.loc["1.5_Rule", column] = 1.5 * descriptive[column]["IQR"]
    descriptive.loc["Lower_Boundary", column] = descriptive[column]["Q1:25%"] - descriptive[column]["1.5_Rule"]
    descriptive.loc["Upper_Boundary", column] = descriptive[column]["Q3:75%"] + descriptive[column]["1.5_Rule"]
    descriptive.loc["Min", column] = dataset.describe()[column]["min"]
    descriptive.loc["Max", column] = dataset.describe()[column]["max"]
    descriptive.loc["Has_Lower_Outlier", column] = dataset[column].min() < descriptive.loc["Lower_Boundary", column]
    descriptive.loc["Has_Upper_Outlier", column] = dataset[column].max() > descriptive.loc["Upper_Boundary", column]

In [206]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5_Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lower_Boundary,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Upper_Boundary,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1.0,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
Has_Lower_Outlier,False,False,True,False,False,False,False
Has_Upper_Outlier,False,False,True,True,False,False,True

In [207]:
def has_outliers(quan):
    lower = []
    upper = []
    
    for column in quan:
    	if (dataset[column] < descriptive.loc["Lower_Boundary", column]).any():
    		lower.append(column)
    	if (dataset[column] > descriptive.loc["Upper_Boundary", column]).any():
    		upper.append(column)

    return len(lower) > 0 or len(upper)

In [208]:
# Check the dataset has outliers, BEFORE replacing the lower/upper boundary values
result = has_outliers(quan)
print("Has outliers in the dataset" if result else "Doesn't have dataset")

Has outliers in the dataset

### Replacing Outliers

In [209]:
for column in quan:
    lower = descriptive.loc["Lower_Boundary", column]
    upper = descriptive.loc["Upper_Boundary", column]

    dataset.loc[dataset[column] < lower, column] = lower
    dataset.loc[dataset[column] > upper, column] = upper

In [210]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,390000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,390000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [212]:
# Check the dataset has outliers, AFTER replacing the lower/upper boundary values
result = has_outliers(quan)
print("Has outliers in the dataset" if result else "Doesn't have the outliers in dataset")

Doesn't have the outliers in dataset

In [ ]:
# Dataset is clear after replacement