### Percentile
- NumPy is a library to handle numerical calulations
- np.percentile(dataset, percentage_val)

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("Placement.csv")

In [3]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [4]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [5]:
dataset["hsc_s"].value_counts()

Commerce    113
Science      91
Arts         11
Name: hsc_s, dtype: int64

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [7]:
dataset.describe()
# It will show only for numerical data (Since its applicable for numbers)

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [8]:
np.percentile(dataset["ssc_p"], 10)
# 10% of the data falls under the 52 marks

52.0

In [9]:
np.percentile(dataset["ssc_p"], 15)
# 15% of the data falls under the 55 marks

55.0

In [10]:
np.percentile(dataset["ssc_p"], 50)
# 50% of the data falls under the 67 marks, which is also same as median (mid point) value

67.0

In [11]:
np.percentile(dataset["ssc_p"], 75)
# 75% of the data falls under the 75.7 marks

75.7

In [12]:
# JUST CHECKING FOR 150% (of course data out of range)
# np.percentile(dataset["ssc_p"], 150)
# ValueError: Percentiles must be in the range [0, 100]

In [13]:
val_99 = np.percentile(dataset["ssc_p"], 99)
val_100 = np.percentile(dataset["ssc_p"], 100)

print("Value at 99% is {}, and at 100% is {}".format(val_99, val_100))

Value at 99% is 87.0, and at 100% is 89.4

In [14]:
from Univariate import Univariate 

qual, quan = Univariate.get_qual_quan(dataset)

In [27]:
descriptive = pd.DataFrame(
    index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%","Q4:100%"],
    columns=quan
)

In [28]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()
    descriptive[column]["Mode"] = dataset[column].mode()[0]

In [29]:
descriptive

        sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean      108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median    108       67       65       66       71       62  265000
Mode        1       62       63       65       60     56.7  300000
Q1:25%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q2:50%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q3:75%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
99%       NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q4:100%   NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [30]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()
    descriptive[column]["Mode"] = dataset[column].mode()[0]
    descriptive[column]["Q1:25%"] = np.percentile(dataset[column], 25)

In [31]:
descriptive

        sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean      108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median    108       67       65       66       71       62  265000
Mode        1       62       63       65       60     56.7  300000
Q1:25%   54.5     60.6     60.9       61       60   57.945     NaN
Q2:50%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q3:75%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
99%       NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q4:100%   NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [32]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()
    descriptive[column]["Mode"] = dataset[column].mode()[0]
    descriptive[column]["Q1:25%"] = np.percentile(dataset[column], 25)
    descriptive[column]["Q2:50%"] = np.percentile(dataset[column], 50)

In [33]:
descriptive

        sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean      108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median    108       67       65       66       71       62  265000
Mode        1       62       63       65       60     56.7  300000
Q1:25%   54.5     60.6     60.9       61       60   57.945     NaN
Q2:50%    108       67       65       66       71       62     NaN
Q3:75%    NaN      NaN      NaN      NaN      NaN      NaN     NaN
99%       NaN      NaN      NaN      NaN      NaN      NaN     NaN
Q4:100%   NaN      NaN      NaN      NaN      NaN      NaN     NaN

In [34]:
for column in quan:
    descriptive[column]["Mean"] = dataset[column].mean()
    descriptive[column]["Median"] = dataset[column].median()
    descriptive[column]["Mode"] = dataset[column].mode()[0]
    
    # descriptive[column]["Q1:25%"] = np.percentile(dataset[column], 25)
    # descriptive[column]["Q2:50%"] = np.percentile(dataset[column], 50)
    # descriptive[column]["Q3:75%"] = np.percentile(dataset[column], 75)
    # descriptive[column]["Q3:100%"] = np.percentile(dataset[column], 100)
    
    # following will handle the NaN/missing values
    descriptive[column]["Q1:25%"] = dataset.describe()[column]["25%"]
    descriptive[column]["Q2:50%"] = dataset.describe()[column]["50%"]
    descriptive[column]["Q3:75%"] = dataset.describe()[column]["75%"]
    descriptive[column]["99%"] = np.percentile(dataset[column], 99)
    descriptive[column]["Q4:100%"] = dataset.describe()[column]["max"]

In [35]:
descriptive

          sl_no    ssc_p    hsc_p degree_p  etest_p    mba_p  salary
Mean        108  67.3034  66.3332  66.3702  72.1006  62.2782  288655
Median      108       67       65       66       71       62  265000
Mode          1       62       63       65       60     56.7  300000
Q1:25%     54.5     60.6     60.9       61       60   57.945  240000
Q2:50%      108       67       65       66       71       62  265000
Q3:75%    161.5     75.7       73       72     83.5   66.255  300000
99%      212.86       87    91.86    83.86       97  76.1142     NaN
Q4:100%     215     89.4     97.7       91       98    77.89  940000