### ### Histogram | Skewness | Kurtosis

In [48]:
import numpy as np
import pandas as pd

In [49]:
dataset = pd.read_csv("Placement.csv")

In [50]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [51]:
dataset.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='object')

In [52]:
from Univariate import Univariate 

qual, quan = Univariate.get_qual_quan(dataset)

In [53]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [54]:
# Create frequency table
freq_table = pd.DataFrame(
    columns=["Unique_Values", "Frequency", "Relative_Frequency", "Cumulative_Relative_Frequency"],
)

freq_table

Empty DataFrame
Columns: [Unique_Values, Frequency, Relative_Frequency, Cumulative_Relative_Frequency]
Index: []

In [55]:
freq_table["Unique_Values"]=dataset["ssc_p"].value_counts().index
freq_table

     Unique_Values Frequency Relative_Frequency Cumulative_Relative_Frequency
0            62.00       NaN                NaN                           NaN
1            63.00       NaN                NaN                           NaN
2            67.00       NaN                NaN                           NaN
3            73.00       NaN                NaN                           NaN
4            52.00       NaN                NaN                           NaN
..             ...       ...                ...                           ...
98           55.68       NaN                NaN                           NaN
99           41.00       NaN                NaN                           NaN
100          83.33       NaN                NaN                           NaN
101          43.00       NaN                NaN                           NaN
102          80.60       NaN                NaN                           NaN

[103 rows x 4 columns]

In [56]:
freq_table["Unique_Values"]=dataset["ssc_p"].value_counts().index
freq_table["Frequency"]=dataset["ssc_p"].value_counts().values

freq_table

     Unique_Values  Frequency Relative_Frequency Cumulative_Relative_Frequency
0            62.00         11                NaN                           NaN
1            63.00         10                NaN                           NaN
2            67.00          9                NaN                           NaN
3            73.00          9                NaN                           NaN
4            52.00          9                NaN                           NaN
..             ...        ...                ...                           ...
98           55.68          1                NaN                           NaN
99           41.00          1                NaN                           NaN
100          83.33          1                NaN                           NaN
101          43.00          1                NaN                           NaN
102          80.60          1                NaN                           NaN

[103 rows x 4 columns]

In [57]:
freq_table["Unique_Values"]=dataset["ssc_p"].value_counts().index
freq_table["Frequency"]=dataset["ssc_p"].value_counts().values
freq_table["Relative_Frequency"]=freq_table["Frequency"]/len(dataset)

freq_table

,Unique_Values,Frequency,Relative_Frequency,Cumulative_Relative_Frequency
0,62.00,11,0.051163,NaN
1,63.00,10,0.046512,NaN
2,67.00,9,0.041860,NaN
3,73.00,9,0.041860,NaN
4,52.00,9,0.041860,NaN
...,...,...,...,...
98,55.68,1,0.004651,NaN
99,41.00,1,0.004651,NaN
100,83.33,1,0.004651,NaN
101,43.00,1,0.004651,NaN
102,80.60,1,0.004651,NaN

In [58]:
freq_table["Unique_Values"]=dataset["ssc_p"].value_counts().index
freq_table["Frequency"]=dataset["ssc_p"].value_counts().values
freq_table["Relative_Frequency"]=freq_table["Frequency"]/len(dataset)
freq_table["Cumulative_Relative_Frequency"]=freq_table["Relative_Frequency"].cumsum()

freq_table

,Unique_Values,Frequency,Relative_Frequency,Cumulative_Relative_Frequency
0,62.00,11,0.051163,0.051163
1,63.00,10,0.046512,0.097674
2,67.00,9,0.041860,0.139535
3,73.00,9,0.041860,0.181395
4,52.00,9,0.041860,0.223256
...,...,...,...,...
98,55.68,1,0.004651,0.981395
99,41.00,1,0.004651,0.986047
100,83.33,1,0.004651,0.990698
101,43.00,1,0.004651,0.995349
102,80.60,1,0.004651,1.000000

In [59]:
# create a function
def get_freq_table(column, dataset):
    freq_table = pd.DataFrame(
        columns=["Unique_Values", "Frequency", "Relative_Frequency", "Cumulative_Relative_Frequency"],
    )
    
    freq_table["Unique_Values"]=dataset[column].value_counts().index
    freq_table["Frequency"]=dataset[column].value_counts().values
    freq_table["Relative_Frequency"]=freq_table["Frequency"]/len(dataset)
    freq_table["Cumulative_Relative_Frequency"]=freq_table["Relative_Frequency"].cumsum()
    
    return freq_table

In [60]:
get_freq_table("hsc_p", dataset)

,Unique_Values,Frequency,Relative_Frequency,Cumulative_Relative_Frequency
0,63.00,14,0.065116,0.065116
1,62.00,12,0.055814,0.120930
2,60.00,9,0.041860,0.162791
3,67.00,9,0.041860,0.204651
4,64.00,8,0.037209,0.241860
...,...,...,...,...
92,77.60,1,0.004651,0.981395
93,70.20,1,0.004651,0.986047
94,61.40,1,0.004651,0.990698
95,61.33,1,0.004651,0.995349
96,42.00,1,0.004651,1.000000

In [61]:
# dir(dataset["ssc_p"])

In [62]:
dataset["ssc_p"].skew()

np.float64(-0.13264949031456927)

In [63]:
dataset["ssc_p"].kurtosis()

np.float64(-0.6075102066986688)

In [64]:
from Univariate import Univariate 

qual, quan = Univariate.get_qual_quan(dataset)

In [65]:
descriptive = pd.DataFrame(
    index=[
        "Mean", "Median", "Mode", 
        # "Q1:25%", "Q2:50%", "Q3:75%", "99%","Q4:100%", 
        # "IQR", "1.5_Rule", "Lower_Boundary", "Upper_Boundary", "Min", "Max",
        # "Has_Lower_Outlier",
        # "Has_Upper_Outlier",
        "Skewness", "Kurtosis"
    ],
    columns=quan
)

In [66]:
for column in quan:
    descriptive.loc["Mean", column] = dataset[column].mean()
    descriptive.loc["Median", column] = dataset[column].median()
    descriptive.loc["Mode", column] = dataset[column].mode()[0]
    
    # following will handle the NaN/missing values
    # descriptive.loc["Q1:25%", column] = dataset.describe()[column]["25%"]
    # descriptive.loc["Q2:50%", column] = dataset.describe()[column]["50%"]
    # descriptive.loc["Q3:75%", column] = dataset.describe()[column]["75%"]
    # descriptive.loc["99%", column] = np.percentile(dataset[column], 99)
    # descriptive.loc["Q4:100%", column] = dataset.describe()[column]["max"]

    # IQR
    # descriptive.loc["IQR", column] = descriptive[column]["Q3:75%"] - descriptive[column]["Q1:25%"]
    # descriptive.loc["1.5_Rule", column] = 1.5 * descriptive[column]["IQR"]
    # descriptive.loc["Lower_Boundary", column] = descriptive[column]["Q1:25%"] - descriptive[column]["1.5_Rule"]
    # descriptive.loc["Upper_Boundary", column] = descriptive[column]["Q3:75%"] + descriptive[column]["1.5_Rule"]
    # descriptive.loc["Min", column] = dataset.describe()[column]["min"]
    # descriptive.loc["Max", column] = dataset.describe()[column]["max"]
    # descriptive.loc["Has_Lower_Outlier", column] = dataset[column].min() < descriptive.loc["Lower_Boundary", column]
    # descriptive.loc["Has_Upper_Outlier", column] = dataset[column].max() > descriptive.loc["Upper_Boundary", column]

    # Skewness/Kurtosis
    descriptive.loc["Skewness", column] = dataset[column].skew()
    descriptive.loc["Kurtosis", column] = dataset[column].kurtosis()

In [67]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Skewness,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
Kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273